/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          card: 'var(--color-card)',
          border: 'var(--color-border)',
          text: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          sub: 'var(--color-text-sub)',
        },
        ochre: {
          DEFAULT: 'var(--color-accent)',
          dim: 'var(--color-accent-dim)',
          light: '#F5C26B',
          dark: '#935805',
        },
        teal: {
          DEFAULT: 'var(--color-accent-2)',
          dim: 'var(--color-accent-2-dim)',
        },
        electric: {
          DEFAULT: 'var(--color-accent)',
          400: 'var(--color-accent)',
          500: 'var(--color-accent)',
          600: 'var(--color-accent-dim)',
          dim: 'var(--color-accent-dim)',
        },
        obsidian: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          card: 'var(--color-card)',
          variant: 'var(--color-surface)',
          border: 'var(--color-border)',
          subtle: 'var(--color-surface)',
        },
        dark: {
          bg: 'var(--color-bg)',
          surface: 'var(--color-surface)',
          card: 'var(--color-card)',
          variant: 'var(--color-surface)',
          border: 'var(--color-border)',
          subtle: 'var(--color-surface)',
          text: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          sub: 'var(--color-text-sub)',
        },
        category: {
          dsa: '#2563EB',
          system_design: '#7C3AED',
          databases: '#0D9488',
          operating_systems: '#EA580C',
          networking: '#16A34A',
          oop_design_patterns: '#DB2777',
          frontend: '#CA8A04',
          backend: '#0284C7',
          devops_infra: '#059669',
          security: '#E11D48',
          testing_qa: '#15803D',
          version_control: '#9333EA',
          cloud: '#2563EB',
          ml_basics: '#C026D3',
          behavioral_interview: '#D97706',
          language_specific: '#0F766E',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
        display: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
      animation: {
        'marquee': 'marquee 25s linear infinite',
        'marquee-reverse': 'marquee-reverse 25s linear infinite',
        'shine': 'shine 3.5s linear infinite',
        'fadeIn': 'fadeIn 0.2s ease-out forwards',
        'laserTrace': 'laserTrace 2.6s ease-in-out infinite',
      },
      keyframes: {
        laserTrace: {
          '0%': { strokeDashoffset: '220', opacity: '0.2' },
          '30%': { opacity: '1' },
          '50%': { strokeDashoffset: '0', opacity: '1' },
          '80%': { strokeDashoffset: '-220', opacity: '1' },
          '100%': { strokeDashoffset: '-220', opacity: '0.2' },
        },
        shine: {
          '0%': { 'background-position': '100%' },
          '100%': { 'background-position': '-100%' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        },
      },
    },
  },
  plugins: [],
};
