import { Concept } from '../types';

export const seedConceptsDatabases: Concept[] = [
  {
    id: 'concept-acid-properties',
    slug: 'acid-properties-transactions',
    title: 'ACID Properties & Transaction Guarantees',
    oneLiner: 'Four core guarantees (Atomicity, Consistency, Isolation, Durability) ensuring reliable relational transactions.',
    category: 'databases',
    difficulty: 'beginner',
    tagIds: ['tag-databases', 'tag-sql', 'tag-transactions'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 80,
    askedByCompanies: ['Amazon', 'Microsoft', 'Oracle', 'Goldman Sachs'],
    relatedConceptIds: ['concept-database-sharding', 'concept-mvcc-isolation'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'Four quadrant diagram visualizing Atomicity, Consistency, Isolation, and Durability.',
    body: {
      definition: 'ACID is a set of properties that guarantee database transactions are processed reliably: Atomicity (all-or-nothing), Consistency (state invariants), Isolation (concurrency control), and Durability (persistence on disk).',
      whyItMatters: 'Guarantees data integrity during server crashes, hardware failures, power outages, and high-concurrency conflicting operations like money transfers.',
      example: 'BEGIN TRANSACTION;\n  UPDATE accounts SET balance = balance - 100 WHERE id = "A";\n  UPDATE accounts SET balance = balance + 100 WHERE id = "B";\nCOMMIT; -- Flushed to Write-Ahead Log (WAL) on disk',
      commonPitfall: 'Confusing ACID Consistency (domain constraints like non-negative balances) with CAP theorem Consistency (linearizability/single-copy atomic view).',
      interviewAngle: 'Tested through isolation anomalies (dirty reads, non-repeatable reads, phantom reads) and write-ahead logging (WAL) mechanics.',
      quickChecks: [
        {
          question: 'What happens if a server loses power mid-transaction before COMMIT?',
          answer: 'On recovery, the database uses undo logs in the WAL to roll back partial writes (Atomicity).',
        },
        {
          question: 'How is Durability achieved without synchronous B-Tree disk writes?',
          answer: 'By sequentially appending records to the Write-Ahead Log (WAL) before acknowledging the client.',
        },
      ],
    },
  },
  {
    id: 'concept-database-indexing-b-trees',
    slug: 'database-indexing-b-trees',
    title: 'B+ Tree Indexing & Query Execution',
    oneLiner: 'Self-balancing multi-way search tree storing records in linked leaf pages for O(log n) point and range queries.',
    category: 'databases',
    difficulty: 'intermediate',
    tagIds: ['tag-databases', 'tag-indexing', 'tag-performance'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 85,
    askedByCompanies: ['Google', 'Meta', 'PostgreSQL', 'Uber'],
    relatedConceptIds: ['concept-acid-properties', 'concept-database-sharding'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'B+ Tree structure with internal routing nodes and doubly linked sequential leaf nodes.',
    body: {
      definition: 'A B+ Tree is a self-balancing search tree where internal nodes store routing keys and all actual data pointers are kept in sorted leaf nodes linked sequentially for fast range scans.',
      whyItMatters: 'Maximizes disk block I/O efficiency with high fan-out (thousands of child pointers per page), keeping tree depth to 3-4 levels for billions of rows with O(log n) lookup.',
      example: '-- Composite Index Creation\nCREATE INDEX idx_users_org_created ON users(org_id, created_at);\n\n-- Uses index efficiently (Leftmost Prefix Rule)\nSELECT * FROM users WHERE org_id = "101" AND created_at > "2026-01-01";',
      commonPitfall: 'Violating the Leftmost Prefix Rule on composite indexes (e.g. querying without the first column forces a full table scan).',
      interviewAngle: 'Standard questions on clustered vs secondary indexes, index selectivity, covering indexes, and explaining EXPLAIN ANALYZE plans.',
      quickChecks: [
        {
          question: 'Why do B+ trees keep all data in leaf nodes rather than internal nodes?',
          answer: 'Higher internal node fan-out reduces tree depth, minimizing expensive disk I/O operations.',
        },
        {
          question: 'Why are B+ Tree leaf nodes doubly linked?',
          answer: 'To allow fast sequential forward and backward range scans without traversing tree roots.',
        },
      ],
    },
  },
  {
    id: 'concept-mvcc-isolation',
    slug: 'mvcc-isolation-levels',
    title: 'MVCC & Transaction Isolation Levels',
    oneLiner: 'Concurrency control mechanism providing snapshot isolation without blocking concurrent readers and writers.',
    category: 'databases',
    difficulty: 'advanced',
    tagIds: ['tag-databases', 'tag-concurrency', 'tag-transactions'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 90,
    askedByCompanies: ['Meta', 'Amazon', 'Stripe', 'CockroachDB'],
    relatedConceptIds: ['concept-acid-properties'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'MVCC version chain showing row creation and expiration transaction timestamps.',
    body: {
      definition: 'Multi-Version Concurrency Control (MVCC) maintains multiple physical versions of a data row, allowing transactions to read consistent point-in-time snapshots without acquiring shared read locks.',
      whyItMatters: 'Eliminates read-write locking contention: "Readers do not block writers, and writers do not block readers." Powers modern Postgres, MySQL InnoDB, and Oracle engines.',
      example: '-- Row Versioning tuple structure\n-- (xmin: creation_tx_id, xmax: deletion_tx_id, payload)\n-- Tx 100: INSERT -> (xmin=100, xmax=0, "Active")\n-- Tx 105: UPDATE -> (xmin=100, xmax=105, "Active"), (xmin=105, xmax=0, "Pending")',
      commonPitfall: 'Neglecting VACUUM / garbage collection, leading to table bloat as dead row tuples accumulate after heavy UPDATE/DELETE workloads.',
      interviewAngle: 'Tested via the 4 ANSI SQL isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable) and Write Skew anomalies.',
      quickChecks: [
        {
          question: 'What is a Dirty Read?',
          answer: 'Reading uncommitted modifications made by another concurrent transaction.',
        },
        {
          question: 'How does MVCC enable lock-free reads?',
          answer: 'By serving historical row versions visible to the transaction snapshot timestamp.',
        },
      ],
    },
  },
];
