import { Course } from '../types';

export const seedCourses: Course[] = [
  {
    id: 'course-system-design-fundamentals',
    slug: 'system-design-fundamentals',
    title: 'System Design Fundamentals',
    description: 'Master core architectural building blocks: distributed consistency, consistent hashing, rate limiting, and database partitioning.',
    primaryCategory: 'system_design',
    difficulty: 'intermediate',
    conceptIds: [
      'concept-cap-theorem',
      'concept-consistent-hashing',
      'concept-rate-limiting',
      'concept-database-sharding',
      'concept-event-sourcing',
    ],
    totalReadSeconds: 450,
    coverImageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    status: 'published',
    source: 'human_curated',
    startedCount: 1420,
    completedCount: 890,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'course-dsa-core-patterns',
    slug: 'dsa-core-patterns',
    title: 'DSA Core Patterns',
    description: 'Key algorithmic building blocks every software engineer must know: Binary Search, LRU Caching, Graph Traversals, and Trie trees.',
    primaryCategory: 'dsa',
    difficulty: 'intermediate',
    conceptIds: [
      'concept-binary-search',
      'concept-lru-cache',
      'concept-graph-bfs-dfs',
      'concept-trie',
    ],
    totalReadSeconds: 345,
    coverImageUrl: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=800&auto=format&fit=crop&q=80',
    status: 'published',
    source: 'human_curated',
    startedCount: 2310,
    completedCount: 1640,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'course-backend-reliability',
    slug: 'backend-reliability-architecture',
    title: 'Backend Reliability & Architecture',
    description: 'Build bulletproof backend services: network handshakes, concurrency paradigms, circuit breakers, idempotency, and zero-downtime releases.',
    primaryCategory: 'backend',
    difficulty: 'intermediate',
    conceptIds: [
      'concept-tcp-handshake',
      'concept-concurrency-parallelism',
      'concept-circuit-breaker',
      'concept-idempotency',
      'concept-zero-downtime',
    ],
    totalReadSeconds: 430,
    coverImageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    status: 'published',
    source: 'human_curated',
    startedCount: 980,
    completedCount: 520,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];
