import { Concept } from '../types';

export const seedConceptsPatterns: Concept[] = [
  {
    id: 'concept-dependency-injection',
    slug: 'dependency-injection',
    title: 'Dependency Injection',
    oneLiner: 'Design pattern supplying required dependencies from the outside rather than instantiating them internally.',
    category: 'oop_design_patterns',
    difficulty: 'beginner',
    tagIds: ['tag-design-patterns', 'tag-reliability'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 80,
    askedByCompanies: ['Google', 'Microsoft', 'Uber'],
    relatedConceptIds: ['concept-circuit-breaker'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: false,
    body: {
      definition: 'A technique where an object receives its dependencies from an external assembler (inversion of control) rather than hardcoding their creation.',
      whyItMatters: 'Decouples components, makes code modular, and allows effortless mocking of services for isolated unit testing.',
      example: 'class UserService {\n  constructor(private repo: UserRepository) {}\n}',
      commonPitfall: 'Overusing service locators or complex reflection DI containers where simple constructor injection suffices.',
      interviewAngle: 'Discuss how Dependency Inversion Principle (DIP in SOLID) relates to Dependency Injection.',
      quickChecks: [
        {
          question: 'What is the primary benefit of dependency injection in automated testing?',
          answer: 'Allows swapping concrete network/database implementations with mock objects.',
        },
        {
          question: 'What principle of SOLID does DI directly support?',
          answer: 'The Dependency Inversion Principle.',
        },
      ],
    },
  },
  {
    id: 'concept-circuit-breaker',
    slug: 'circuit-breaker-pattern',
    title: 'Circuit Breaker Pattern',
    oneLiner: 'Resilience pattern preventing cascading service failures by failing fast when downstream services are unhealthy.',
    category: 'backend',
    difficulty: 'intermediate',
    tagIds: ['tag-reliability', 'tag-design-patterns', 'tag-distributed-systems'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 90,
    askedByCompanies: ['Netflix', 'Amazon', 'Stripe'],
    relatedConceptIds: ['concept-idempotency'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'Finite state machine diagram with Closed, Open, and Half-Open states and transition failure thresholds.',
    body: {
      definition: 'A design pattern wrapping calls to downstream services with 3 states: Closed (normal), Open (failing fast without calling), and Half-Open (trial testing).',
      whyItMatters: 'Prevents server thread pool exhaustion and cascading distributed outages when a third-party dependency is down.',
      example: 'if (circuit.isOpen()) return cachedFallback();\ntry { return await remoteCall(); } catch (err) { circuit.recordFail(); }',
      commonPitfall: 'Not providing a sensible fallback response or fallback cache when the circuit is in Open state.',
      interviewAngle: 'Walk through the transition triggers between Closed, Open, and Half-Open states.',
      quickChecks: [
        {
          question: 'What are the 3 states of a Circuit Breaker?',
          answer: 'Closed (healthy), Open (fail fast), and Half-Open (probe recovery).',
        },
        {
          question: 'What resource does a circuit breaker prevent exhausting?',
          answer: 'Thread pools, connection pools, and client sockets.',
        },
      ],
    },
  },
  {
    id: 'concept-idempotency',
    slug: 'api-idempotency',
    title: 'API Idempotency',
    oneLiner: 'Property of an API endpoint where making the same request multiple times produces the exact same outcome.',
    category: 'backend',
    difficulty: 'intermediate',
    tagIds: ['tag-api-design', 'tag-reliability'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 85,
    askedByCompanies: ['Stripe', 'PayPal', 'Shopify'],
    relatedConceptIds: ['concept-circuit-breaker'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: false,
    body: {
      definition: 'An operation is idempotent if executing it once or multiple identical times has the same intended effect and leaves system state unchanged.',
      whyItMatters: 'Essential in payment processing and distributed retries so that network timeouts do not cause duplicate credit card charges.',
      example: 'Client sends header Idempotency-Key: req_123abc. Server stores key atomically; duplicate calls return cached result.',
      commonPitfall: 'Assuming HTTP POST is naturally idempotent. POST requires explicit idempotency keys; GET/PUT/DELETE are naturally idempotent.',
      interviewAngle: 'Design an idempotent charge API handling concurrent identical requests and database locks.',
      quickChecks: [
        {
          question: 'Which HTTP methods are naturally idempotent by RFC specification?',
          answer: 'GET, PUT, DELETE, and HEAD.',
        },
        {
          question: 'How do modern payment APIs guarantee idempotency on POST requests?',
          answer: 'By requiring unique client-generated Idempotency Keys.',
        },
      ],
    },
  },
  {
    id: 'concept-zero-downtime',
    slug: 'zero-downtime-deployment',
    title: 'Zero-Downtime Deployment',
    oneLiner: 'Release strategies updating production software without interrupting user traffic or dropping requests.',
    category: 'devops_infra',
    difficulty: 'intermediate',
    tagIds: ['tag-devops', 'tag-ci-cd', 'tag-reliability'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 90,
    askedByCompanies: ['Netflix', 'AWS', 'Spotify'],
    relatedConceptIds: ['concept-circuit-breaker'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'Load balancer switching traffic router seamlessly from Blue environment to Green environment.',
    body: {
      definition: 'Deployment methodologies (Blue-Green, Canary, Rolling) that release new versions while active instances continuously serve live user traffic.',
      whyItMatters: 'Eliminates maintenance windows, maximizes uptime SLAs, and allows continuous deployment multiple times per day with safe rollback.',
      example: 'Blue-Green: Blue (v1) receives 100% traffic. Green (v2) is deployed and health-checked. Router switches load balancer target to Green in 1 second.',
      commonPitfall: 'Making backwards-incompatible database schema changes (e.g. dropping columns) before rolling out application code.',
      interviewAngle: 'Explain the Expand and Contract pattern for zero-downtime database migrations.',
      quickChecks: [
        {
          question: 'What is Blue-Green deployment?',
          answer: 'Running two identical production environments and switching traffic via load balancer.',
        },
        {
          question: 'How do you safely migrate database columns without downtime?',
          answer: 'Use Expand & Contract: add new column, dual write, backfill, switch reads, drop old column.',
        },
      ],
    },
  },
  {
    id: 'concept-raft-consensus',
    slug: 'raft-consensus',
    title: 'Raft Consensus Algorithm',
    oneLiner: 'Leader-based distributed consensus protocol designed for understandable fault-tolerant state machine replication.',
    category: 'system_design',
    difficulty: 'advanced',
    tagIds: ['tag-distributed-systems', 'tag-reliability'],
    status: 'published',
    source: 'human_curated',
    estimatedReadSeconds: 95,
    askedByCompanies: ['HashiCorp', 'CockroachDB', 'CoreOS'],
    relatedConceptIds: ['concept-cap-theorem'],
    createdAt: '2026-01-02T00:00:00.000Z',
    updatedAt: '2026-01-02T00:00:00.000Z',
    visualAid: true,
    heroImageUrl: null,
    imagePrompt: 'State diagram showing Leader, Follower, and Candidate states with election timeout timers.',
    body: {
      definition: 'A consensus algorithm that elects a leader to manage log replication across a cluster, ensuring nodes agree on state transitions despite node failures.',
      whyItMatters: 'Powers modern distributed databases and control planes like etcd (Kubernetes), Consul, and CockroachDB.',
      example: 'Nodes transition from Follower -> Candidate on heartbeat timeout -> Leader when majority votes received.',
      commonPitfall: 'Split-vote scenarios when election timeouts are not randomized across nodes.',
      interviewAngle: 'Compare Raft log replication and leader election with Multi-Paxos.',
      quickChecks: [
        {
          question: 'What are the three node roles in Raft?',
          answer: 'Leader, Follower, and Candidate.',
        },
        {
          question: 'How is split-vote mitigated during leader elections in Raft?',
          answer: 'By utilizing randomized election timeouts.',
        },
      ],
    },
  },
];
